### ISSUE TITLE
Could you please share some trained params?

### ISSUE THREAD

**Issue by liusongxiang** [azraelkuan/tensorflow_wavenet_vocoder#4]
Dear Kuan Chen,
Could you please share your checkpoints for the LJspeech and CMU_arctic, as well as the corresponding hparams settings? That will be much helpful for me.
Thank you in advance!

Songxiang Liu

**Comment by azraelkuan** [comment]
https://pan.baidu.com/s/1q6mOMt11HWdZVHWIuT7sKQ this is a checkpoint of 8 bit multi speakers of cmu arctic, the setting is `hparams.py` as default

**Comment by liusongxiang** [comment]
Thank you very much!
