### ISSUE TITLE
Do your project generate raw speech samples from acoustic features, or from text, like TTS?

### ISSUE THREAD

**Issue by HudsonHuang** [azraelkuan/tensorflow_wavenet_vocoder#5]
I found this project is trying to generate raw speech samples from acoustic features like previous vocoders (WORLD,DIO,etc.)
https://github.com/r9y9/wavenet_vocoder

But it seems your project is to generate waveform and conditioned by text files?

It's input might different with the traditional one, right?

**Comment by azraelkuan** [comment]
@HudsonHuang yes，you can change the input to hts-like label vector, it can generate wav from text.
i am sorry about the late reply. because i have re-implement a new version of tensorflow wavenet include parallel but it is a intern project.

**Comment by HudsonHuang** [comment]
Thank you very much for the clarity of your result, that would be helpful for beginners like me.
